#!/usr/bin/env python3
"""Generate docs/ENVIRONMENT_REFERENCE.md from the code (AST scan).

Every environment variable read by non-test Python code is listed with its
default (when a literal), where it is read, and whether it appears in
``.local-worker.env.example`` / ``render.yaml``.  The output is deterministic;
``tests/test_env_contract_20261007.py`` fails when the file is stale or when a
variable is read by code but documented nowhere.

    python tools/env_reference.py          # rewrite the document
    python tools/env_reference.py --check  # exit 1 when stale
"""
from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "ENVIRONMENT_REFERENCE.md"
NAME_RE = re.compile(r"^[A-Z][A-Z0-9_]{2,}$")
SKIP_DIRS = {"tests", ".git", "__pycache__", "node_modules", ".venv", "venv", "data", "tmp_convert", "archive"}


def _is_env_call(func: ast.expr) -> bool:
    name = func.attr if isinstance(func, ast.Attribute) else func.id if isinstance(func, ast.Name) else ""
    if name == "getenv" or name.startswith("_env") or name in {"env_int", "env_bool", "env_float", "env_text"}:
        return True
    if name == "get" and isinstance(func, ast.Attribute):
        target = func.value
        return (isinstance(target, ast.Attribute) and target.attr == "environ") or (isinstance(target, ast.Name) and target.id in {"env", "environ"})
    return False


def _literal(node: ast.expr | None) -> str:
    if node is None:
        return ""
    try:
        value = ast.literal_eval(node)
    except Exception:
        return ""
    return "" if value is None else str(value)


def scan() -> dict[str, dict]:
    found: dict[str, dict] = {}

    def add(name: str, default: str, path: Path) -> None:
        entry = found.setdefault(name, {"default": "", "files": set()})
        if default and not entry["default"]:
            entry["default"] = default
        entry["files"].add(path.relative_to(ROOT).as_posix())

    for path in sorted(ROOT.rglob("*.py")):
        rel = path.relative_to(ROOT).parts
        if set(rel[:-1]) & SKIP_DIRS or path.name.startswith("test_"):
            continue
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and _is_env_call(node.func) and node.args:
                first = node.args[0]
                # helpers such as _env_true(env, "NAME", default) take the mapping first
                candidates = [a for a in node.args[:2] if isinstance(a, ast.Constant) and isinstance(a.value, str) and NAME_RE.match(a.value)]
                if not candidates:
                    continue
                name_node = candidates[0]
                idx = node.args.index(name_node)
                default = _literal(node.args[idx + 1]) if len(node.args) > idx + 1 else ""
                add(name_node.value, default, path)
            elif isinstance(node, ast.Subscript) and isinstance(node.value, ast.Attribute) and node.value.attr == "environ":
                key = node.slice
                if isinstance(key, ast.Constant) and isinstance(key.value, str) and NAME_RE.match(key.value):
                    add(key.value, "", path)
    return found


def code_literals() -> set[str]:
    """Every ALL_CAPS string literal in non-test code (covers dynamic reads such as tables of names)."""
    names: set[str] = set()
    for path in sorted(ROOT.rglob("*.py")):
        rel = path.relative_to(ROOT).parts
        if set(rel[:-1]) & SKIP_DIRS or path.name.startswith("test_"):
            continue
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError):
            continue
        names.update(n.value for n in ast.walk(tree) if isinstance(n, ast.Constant) and isinstance(n.value, str) and NAME_RE.match(n.value))
    return names


def example_keys() -> set[str]:
    keys: set[str] = set()
    for line in (ROOT / ".local-worker.env.example").read_text(encoding="utf-8").splitlines():
        match = re.match(r"^\s*#?\s*([A-Z][A-Z0-9_]{2,})\s*=", line)
        if match:
            keys.add(match.group(1))
    return keys


def render_keys() -> set[str]:
    return set(re.findall(r"-\s*key:\s*([A-Z][A-Z0-9_]{2,})", (ROOT / "render.yaml").read_text(encoding="utf-8")))


def build() -> str:
    found, example, render = scan(), example_keys(), render_keys()
    lines = [
        "# Environment variable reference",
        "",
        "Generated by `python tools/env_reference.py` — do not edit by hand.",
        "A test fails when this file is stale or when code reads a variable that is documented nowhere.",
        "Narrative documentation: `LOCAL_WORKER_6_7.md`, `docs/WORKER_BOOTSTRAP.md`, `README.md`.",
        "",
        "| Variable | Default (literal) | Read by | In `.local-worker.env.example` | In `render.yaml` |",
        "|---|---|---|---|---|",
    ]
    for name in sorted(found):
        entry = found[name]
        files = sorted(entry["files"])
        read_by = ", ".join(f"`{f}`" for f in files[:3]) + (f" (+{len(files) - 3})" if len(files) > 3 else "")
        default = entry["default"].replace("|", "\\|").replace("\n", " ")[:40]
        lines.append(f"| `{name}` | {'`' + default + '`' if default else ''} | {read_by} | {'yes' if name in example else ''} | {'yes' if name in render else ''} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    text = build()
    if args.check:
        if not DOC.exists() or DOC.read_text(encoding="utf-8") != text:
            print("docs/ENVIRONMENT_REFERENCE.md is stale: run python tools/env_reference.py")
            return 1
        return 0
    DOC.write_text(text, encoding="utf-8")
    print(f"wrote {DOC.relative_to(ROOT)} ({text.count(chr(10)) - 7} variables)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
